!IF "$(IDA_PLATFORM)" == "32"
OBJSUFFIX=.obj32
LIBSUFFIX=.lib
DLLSUFFIX=.dll
IDALIB=x64_win_vc_32\ida.lib
IDACXXFLAGS=/D__X64__
GCCLIKECFLAGS=/D__x86_64
!ELSEIF "$(IDA_PLATFORM)" == "64"
OBJSUFFIX=.obj64
LIBSUFFIX=64.lib
DLLSUFFIX=64.dll
IDALIB=x64_win_vc_64\ida.lib
IDACXXFLAGS=/D__X64__ /D__EA64__
GCCLIKECFLAGS=/D__x86_64
!ELSE
!ERROR Unsupported platform
!ENDIF

CC=cl
CXX=cl
AR=lib
LD=link
RM=del
COMMONCFLAGS=/O2 /W3 $(GCCLIKECFLAGS)
# Use settings below for debug build without optimizations
# COMMONCFLAGS=/Zi /W3 $(GCCLIKECFLAGS)
# LDFLAGS=/DEBUG
COMMONCXXFLAGS=$(COMMONCFLAGS) /EHsc
